# Generated by Django 4.2.24 on 2025-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0003_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
