# Generated by Django 4.2.24 on 2025-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0004_alter_announcement_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
