# Generated by Django 4.2.24 on 2025-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0005_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
