# Generated by Django 4.2.24 on 2025-10-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0006_announcement_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='details',
            new_name='title',
        ),
    ]
