# Generated by Django 4.2.24 on 2025-09-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('marks', models.CharField(blank=True, default=0, max_length=100)),
                ('percentage', models.DateField(blank=True, default=0, max_length=30)),
                ('academic_year', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, default=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
