# Generated by Django 4.2.24 on 2025-09-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='user',
            new_name='teacher',
        ),
    ]
